server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: cloud-provider-consul-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.4.97
      port: 8500
      discovery:
        #hostname: 192.168.4.97
        service-name: ${spring.application.name}

