server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # nacos地址，默认端口8848
        server-addr: 192.168.4.97:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"